apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2020-06-12T14:06:18Z"
    generation: 1
    labels:
      app: automation
    name: automation
    namespace: default
    resourceVersion: "191253"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/automation
    uid: e302b4d8-acb5-11ea-b27e-42010a800058
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: automation
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: automation
      spec:
        containers:
        - image: kurodta/webfront
          imagePullPolicy: Never
          name: webfront
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2020-06-12T14:06:22Z"
      lastUpdateTime: "2020-06-12T14:06:22Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2020-06-12T14:06:18Z"
      lastUpdateTime: "2020-06-12T14:06:22Z"
      message: ReplicaSet "automation-56d95c9bf4" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""