apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2020-07-10T14:14:36Z"
    generation: 1
    name: autocalc-deployment
    namespace: default
    resourceVersion: "945016"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/autocalc-deployment
    uid: af5e75bb-c2b7-11ea-92ea-42010a8001e1
  spec:
    progressDeadlineSeconds: 600
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: autocalc
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: autocalc
      spec:
        containers:
        - env:
          - name: master
            value: "true"
          image: kurodta/testcalc
          imagePullPolicy: Always
          name: autocalc
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /home/docker/ini
            name: config
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: autocalc-ini
          name: config
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2020-07-10T14:14:38Z"
      lastUpdateTime: "2020-07-10T14:14:38Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2020-07-10T14:14:36Z"
      lastUpdateTime: "2020-07-10T14:14:38Z"
      message: ReplicaSet "autocalc-deployment-5b59749ff9" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""